### PR TITLE
include/ssl_compat.h: fix build with libressl >= 3.5.0

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure with libressl >= 3.5.0:

```
In file included from /tmp/instance-10/output-1/build/mariadb-10.3.36/vio/viosslfactories.c:18: /tmp/instance-10/output-1/build/mariadb-10.3.36/vio/viosslfactories.c: In function 'get_dh2048': /tmp/instance-10/output-1/build/mariadb-10.3.36/include/ssl_compat.h:68:45: error: invalid use of incomplete typedef 'DH' {aka 'struct dh_st'}
   68 | #define DH_set0_pqg(D,P,Q,G)            ((D)->p= (P), (D)->g= (G))
      |                                             ^~
```

Fixes:
 - http://autobuild.buildroot.org/results/524198344aafca58d214537af64c5961c407b0f8

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by grooverdan** [comment]
10.3 branch is currently closed to important fixes so I triggered a build against [10.4](https://buildbot.mariadb.org/#/grid?branch=bb-10.4-danielblack-pr2435-libressl). If its stable can you rebase this on 10.4 and edit the base in the github PR title to be 10.4 too.

**Comment by grooverdan** [comment]
Sorry, wasn't clear, both a `git rebase --onto origin/10.4 HEAD^; git push -f` and a editing of the target branch in GH is required.

**Review by grooverdan — APPROVED** [review]
