### PR TITLE
MDEV-37619 The forced use of THD accessors hurts InnoDB performance

### PR DESCRIPTION
**Pull request by dr-m**
- [x] *The Jira issue number for this PR is: MDEV-37619*
## Description
Let InnoDB access some data members of `THD` directly, instead of invoking non-inline accessor functions. Note: `my_thread_id` will be used instead of the potentially narrower `ulong` data type.

Also, let us remove some functions from `sql_class.cc` that were only being used by InnoDB or RocksDB, for no reason. RocksDB always had access to the internals of `THD`.
## Release Notes
The performance of InnoDB was slightly improved.
## How can this PR be tested?
The performance impact has been tested in [MDEV-37152](https://jira.mariadb.org/browse/MDEV-37152) as part of #4252.

The modified code should be well exercised by the default regression tests. No change in behaviour is expected.
## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature or a refactoring, and the PR is based against the `main` branch.*
- [ ] *This is a bug fix, and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

I believe that this would benefit the 10.6 branch as well, but there are several other performance fixes that were already omitted from the 10.6 branch.
## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Comment by dr-m** [comment]
For the record, a `cmake -DPLUGIN_INNOBASE=DYNAMIC` build would fail both before and after these changes. Setting `cmake -DWITH_WSREP=OFF` would fix most of that, but some problems that were introduced in #3022 and a2d37705ca5a79149b1b064fe3a0be0bbf7eaf73. Below are some compiler messages for f609dbd39b54aa5f12adf04f5335197a244284bd for `cmake -DPLUGIN_INNOBASE=DYNAMIC -DWITH_WSREP=OFF`:
```
storage/innobase/handler/ha_innodb.cc: In function ‘void innodb_transaction_abort(THD*, bool, dberr_t)’:
storage/innobase/handler/ha_innodb.cc:2073:31: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
 2073 |     if (thd_log_warnings(thd) >= 4)
storage/innobase/handler/ha_innodb.cc: In member function ‘virtual int ha_innobase::check(THD*, HA_CHECK_OPT*)’:
storage/innobase/handler/ha_innodb.cc:15316:17: error: ‘print_check_msg’ was not declared in this scope
15316 |                 print_check_msg(thd, table->s->db.str, table->s->table_name.str,
      |                 ^~~~~~~~~~~~~~~
```
The first error would actually be fixed by this pull request; `thd->variables.log_warnings` appears to be fine.

File: storage/innobase/lock/lock0lock.cc [hunk 1]
```diff
@@ -1074,7 +1075,7 @@ lock_rec_other_has_expl_req(
 #endif /* UNIV_DEBUG */
 
 #ifdef WITH_WSREP
-void lock_wait_wsrep_kill(trx_t *bf_trx, ulong thd_id, trx_id_t trx_id);
+void lock_wait_wsrep_kill(trx_t *bf_trx, my_thread_id thd_id, trx_id_t trx_id);
```
Comment (mariadb-SaahilAlam) [inline storage/innobase/lock/lock0lock.cc:1078]:
```
Please check if this Assertion is related , it is found during testing :-
GIT_SHOW: HEAD -> MDEV-37619, origin/MDEV-37619 ffc5239ddd9c32031ad364111231f9ee26754e1f
# 2025-09-11T02:50:05 [2187666] | mariadbd: /data/Server/MDEV-37619/storage/innobase/include/sux_lock.h:85: void sux_lock<ssux_lock_impl<true>>::free() [ssux = ssux_lock_impl<true>]: Assertion `r->empty()' failed.

StackTrace:-
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  __GI_abort () at ./stdlib/abort.c:79
#5  __assert_fail_base (fmt="%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry="r->empty()", file=file@entry="/data/Server/MDEV-37619/storage/innobase/include/sux_lock.h", line=line@entry=85, 
    function=function@entry="void sux_lock<ssux_lock_impl<true>>::free() [ssux = ssux_lock_impl<true>]") at ./assert/assert.c:94
#6  __assert_fail (assertion="r->empty()", file="/data/Server/MDEV-37619/storage/innobase/include/sux_lock.h", line=85, function="void sux_lock<ssux_lock_impl<true>>::free() [ssux = ssux_lock_impl<true>]")
    at ./assert/assert.c:103
#7  sux_lock<ssux_lock_impl<true> >::free (this=this@entry=) at /data/Server/MDEV-37619/storage/innobase/include/sux_lock.h:85
#8  dict_index_remove_from_cache_low (table=table@entry=, index=, lru_evict=lru_evict@entry=0) at /data/Server/MDEV-37619/storage/innobase/dict/dict0dict.cc:2156
#9  dict_sys_t::remove (this=<dict_sys>, table=, lru=<optimized out>, keep=false) at /data/Server/MDEV-37619/storage/innobase/dict/dict0dict.cc:1882
#10 innobase_reload_table (table=, ctx=..., thd=<optimized out>, table_name=...) at /data/Server/MDEV-37619/storage/innobase/handler/handler0alter.cc:10663
#11 ha_innobase::commit_inplace_alter_table (this=, altered_table=, ha_alter_info=, commit=<optimized out>) at /data/Server/MDEV-37619/storage/innobase/handler/handler0alter.cc:11855
#12 mysql_inplace_alter_table (thd=thd@entry=, table_list=, table=, altered_table=, ha_alter_info=, target_mdl_request=<optimized out>, ddl_log_state=, trigger_param=, alter_ctx=, partial_alter=false, start_alter_id=0, 
    if_exists=<optimized out>) at /data/Server/MDEV-37619/sql/sql_table.cc:8190
#13 mysql_alter_table (thd=thd@entry=, new_db=<optimized out>, new_name=new_name@entry=, create_info=<optimized out>, table_list=, recreate_info=<optimized out>, alter_info=<optimized out>, order_num=<optimized out>, 
    order=<optimized out>, ignore=<optimized out>, if_exists=<optimized out>) at /data/Server/MDEV-37619/sql/sql_table.cc:11404
#14 Sql_cmd_alter_table::execute (this=<optimized out>, thd=) at /data/Server/MDEV-37619/sql/sql_alter.cc:688
#15 mysql_execute_command (thd=thd@entry=, is_called_from_prepared_stmt=false) at /data/Server/MDEV-37619/sql/sql_parse.cc:6165
#16 mysql_parse (thd=thd@entry=, rawbuf=<optimized out>, length=<optimized out>, parser_state=parser_state@entry=) at /data/Server/MDEV-37619/sql/sql_parse.cc:8180
#17 dispatch_command (command=command@entry=COM_QUERY, thd=thd@entry=, 
    packet=packet@entry=" ALTER TABLE test.t6_p ADD FULLTEXT KEY IF NOT EXISTS `Marvão_ftidx1` ( col_varchar ), LOCK = DEFAULT  /* E_R Thread4 QNO 373 CON_ID 20 */ ", packet_length=packet_length@entry=140, blocking=true)
    at /data/Server/MDEV-37619/sql/sql_parse.cc:1906
#18 do_command (thd=thd@entry=, blocking=<optimized out>) at /data/Server/MDEV-37619/sql/sql_parse.cc:1419
#19 do_handle_one_connection (connect=<optimized out>, connect@entry=, put_in_cache=true) at /data/Server/MDEV-37619/sql/sql_connect.cc:1386
#20 handle_one_connection (arg=) at /data/Server/MDEV-37619/sql/sql_connect.cc:1298
#21 start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#22 clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100

RR trace is present on SDP:-
/data/results/1757572605/TBR-2284A

```

Comment (dr-m) [reply storage/innobase/lock/lock0lock.cc:1078]: The unexpected shared latch was registered by `row_ins_check_foreign_constraint()` in another thread for an `INSERT INTO test.t6_c` statement, checking if a corresponding record exists in this table `t6_p`. This is exactly the scenario of [MDEV-37365](https://jira.mariadb.org/browse/MDEV-37365).

File: storage/innobase/dict/dict0crea.cc [hunk 2]
```diff
@@ -24,6 +24,7 @@ Database object creation
 Created 1/8/1996 Heikki Tuuri
 *******************************************************/
 
+#define MYSQL_SERVER
```
Comment (mariadb-SaahilAlam) [inline storage/innobase/dict/dict0crea.cc:27]:
```
Observed corruption while testing:-
InnoDB: The B-tree of index MarvÃ£o_uidx1 is corrupted

Corruption found on release build while testing MDEV-37619


->/Server_bin/MDEV-37619_RelWithDebInfo<- GIT_SHOW: HEAD -> MDEV-37619, origin/MDEV-37619 ffc5239ddd9c32031ad364111231f9ee26754e1f

# 2025-09-15T07:49:34 [74206] ERROR: Executor: The query ' CHECK TABLE t1 EXTENDED  /* E_R Thread4 QNO 1051 CON_ID 38 */ ' passed but has a result set line 'test.t1 check Warning InnoDB: The B-tree of index MarvÃ£o_uidx1 is corrupted.'.
# 2025-09-15T07:49:34 [74206] ERROR: Executor: Full result of -> CHECK TABLE t1 EXTENDED  /* E_R Thread4 QNO 1051 CON_ID 38 */ <-
# 2025-09-15T07:49:34 [74206] test.t1 check Warning InnoDB: The B-tree of index MarvÃ£o_uidx1 is corrupted.
# 2025-09-15T07:49:34 [74206] test.t1 check error Corrupt
# 2025-09-15T07:49:34 [74206] ERROR: Executor: Will exit with exit status STATUS_DATABASE_CORRUPTION(106).

RR trace is present on pluto:-
/data/results/1757919698/TBR-2332

Bug raised:-https://jira.mariadb.org/browse/MDEV-37659
```

**Review by vuvova — APPROVED** [review]

File: storage/innobase/dict/dict0crea.cc (hunk 2 above)
Comment (dr-m) [reply storage/innobase/dict/dict0crea.cc:27]: I think that this is unrelated to these changes. It appears to be related to a column prefix index in a `PRIMARY KEY`. The table also contains virtual columns and `FULLTEXT INDEX`, which may or may not play a role. In [MDEV-37659](https://jira.mariadb.org/browse/MDEV-37659), I requested a reduced test case or grammar.
