### PR TITLE
innobase: Fix compile error on clang/macOS

### PR DESCRIPTION
**Pull request by shinnok**
On macOS pthread_t is opaque, requires reinterpret_cast since
pthread id is a pointer to struct _opaque_pthread_t type;

Was failing with Clang 10.0.0 Debug build on macOS 10.14:

10.4/storage/innobase/include/ut0counter.h:61:9: error: static_cast from 'os_thread_id_t' (aka '_opaque_pthread_t *') to 'size_t' (aka 'unsigned long') is not allowed
        return static_cast<size_t>(os_thread_get_curr_id());
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Change introduced in:
be31c18e4a6 ib_counter_t code simplified without functional changes

### CODE REVIEW

**Comment by svoj** [comment]
#883

**Comment by svoj** [comment]
There was similar fix where `reinterpret_cast` failed to build. Unfortunately I can't remember where exactly it failed, probably on Windows. E.g. see these patches:
6620fbd62a7465d2aa5010851aabdcd6ec31893f (the fix)
06f539dab5a8009a1feff25f71bee5a27c5c2a63 (revert)
508373d500819864cdfda1695a27e7d615976c2f (new fix)

I merged #883 since it appeared earlier and it appears to be slightly safer.

**Comment by shinnok** [comment]
@svoj sure, I forgot about that. Thanks! :)
