### PR TITLE
[MDEV-33439] Fix build with libxml2 2.12

### PR DESCRIPTION
**Pull request by jtojnar**
- [ ] *The Jira issue number for this PR is: MDEV-33439*

## Description

libxml2 2.12.0 made `xmlGetLastError()` return `const` pointer:

https://gitlab.gnome.org/GNOME/libxml2/-/commit/61034116d0a3c8b295c6137956adc3ae55720711

Clang 16 does not like this:

    error: assigning to 'xmlErrorPtr' (aka '_xmlError *') from 'const xmlError *' (aka 'const _xmlError *') discards qualifiers
    error: cannot initialize a variable of type 'xmlErrorPtr' (aka '_xmlError *') with an rvalue of type 'const xmlError *' (aka 'const _xmlError *')

Let’s update the variables to `const`. For older versions, it will be automatically converted.

But then `xmlResetError(xmlError*)` will not like the `const` pointer:

    error: no matching function for call to 'xmlResetError'
    note: candidate function not viable: 1st argument ('const xmlError *' (aka 'const _xmlError *')) would lose const qualifier

Let’s replace it with `xmlResetLastError()`.

ALso remove `LIBXMLDOC::Xerr` protected member property.
It was introduced in 65b0e5455b547a3d574fa77b34cce23ae3bea0a0 along with the `xmlResetError` calls.
It does not appear to be used for anything.

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to behave as intended.

I tested this on NixOS with Clang 16.0.6 and libxml2 2.12.3.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [x] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

### CODE REVIEW

**Review by grooverdan — APPROVED** [review]
Looks good. Thanks @jtojnar.

Also note to self/other reviewers that [xmlResetLastError](https://github.com/GNOME/libxml2/commit/2b8c4a151bb6bf91c10541b0593218bca5b3d5ce#diff-f2e6c18de8171e389aeff0b8d25b2755253108a59a13baf7167c2ffa0af36a58) was added 21 years ago.

**Comment by LinuxJedi** [comment]
Hi @jtojnar, all looks good to me, many thanks. One thing that we need to do before merging it is rebase against 10.5 instead of 10.4. The reason is 10.4 is approaching EoL and the final release is for critical / security fixes only.

Would you like to do this rebase? Or shall we do?
