### PR TITLE
MDEV-15778: On macOS pthread_t is opaque, requires explicit cast

### PR DESCRIPTION
**Pull request by shinnok**
On macOS pthread id is a pointer to struct _opaque_pthread_t type,
requires explicit cast to ulint which in turn is size_t;
Was failing with Clang 9.1.0 Debug build on macOS 10.13.4:

sync0policy.h:53:4: error: cannot initialize a member subobject of type 'ulint'
(aka 'unsigned long') with an rvalue of type 'os_thread_id_t' (aka '_opaque_pthread_t *')
m_thread_id(os_thread_id_t(ULINT_UNDEFINED))
                        ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sync0policy.h:79:4: error: cannot initialize a parameter of type 'int64' (aka 'long long') with
an rvalue of type 'os_thread_id_t' (aka '_opaque_pthread_t *')
my_atomic_storelint(&m_thread_id, os_thread_get_curr_id());

### CODE REVIEW

**Comment by svoj** [comment]
Hi @shinnok,

Thanks for your contribution! However I don't completely understand why this patch is required. Does recent 10.3 still fail to build on OS X?

Thanks,
Sergey

**Comment by shinnok** [comment]
Hi @svoj, yes this hasn't been fixed. I've added include guard for macOS only. See comments at https://jira.mariadb.org/browse/MDEV-15778. @spetrunia merged to 10.3 then reverted since it failed on Windows and Ubuntu 32bit.

If this is too late for 10.3, maybe change to 10.4.

**Comment by svoj** [comment]
I re-applied it on Sunday. According to bb there're no compilation failures anymore.

**Comment by shinnok** [comment]
@svoj oh I see, you just used c style cast, I missed that in the rebase merge... testing again to see if any diff from reinterpret_cast, but it shouldn't be.
